### ISSUE TITLE
docs now missing

### ISSUE THREAD

**Issue by hturner** [forwards/website_source#135]
With recent changes, we have lost some long-form docs that used to live in a `docs` folder.

When I do 

```quarto publish gh-pages```

I get 

```WARNING: Unable to resolve link target: docs/recommendations_user.md```

**Comment by EllaKaye** [comment]
These files are still on the archive branch so I can rescue them from there, think about where they best fit in the new website structure and make sure all links to them are resolved. 

If it's not urgent, I'd prefer to come back to this towards the end of June (so I can now focus on preparing for the teaching workshop until then). Though, of course, if anyone else would like to do this before then, please go ahead!
