### ISSUE TITLE
atom link in RSS feed

### ISSUE THREAD

**Issue by hturner** [forwards/website_source#17]
atom link should not be relative, currently

    <atom:link href="//forwards.github.io/blog/index.xml" rel="self" type="application/rss+xml" />

**Comment by qinwf** [comment]
I noticed that the new atom feed dose not contains the full posts. Is this expected?

**Comment by hturner** [comment]
Is this since the R in Africa post? I am seeing the full posts on Firefox, in Feedly and in Inoreader.

**Comment by hturner** [comment]
Fixed by forwards/website_source@c50ae2c (need to ensure in-blog links are also fully referenced, i.e. http://... not just www.)
