### ISSUE TITLE
blog on edu page

### ISSUE THREAD

**Issue by hturner** [forwards/website_source#18]
need to sort blog on Edu page, either remove or add separate feed filtered by education category

**Comment by qinwf** [comment]
An RSS feed focuses on edu?

**Comment by hturner** [comment]
At the moment https://forwards.github.io/edu/ just shows an empty post at the bottom of the page. So we should either remove this, or have a display of the blog posts with the "education" category.

We could also offer an RSS feed of just the education posts, but

1. Our blog doesn't have many posts anyway, so there may only be 1 or 2 education ones a year.
2. I'm not sure where we would put it. The link to the RSS underneath the Forwards icon is hard-coded as https://rforwards-auto.github.io/blog/index.xml. We would need to change the page template to have a different feed on the Edu page.

**Comment by hturner** [comment]
Edu page now has summary list of blog posts from Education category
