### ISSUE TITLE
Add photos to About page

### ISSUE THREAD

**Issue by hturner** [forwards/website_source#19]
We could add some photos of Forwards members from useR! 2017

**Comment by emdodwell** [comment]
Where are photos from useR! 2017 (and perhaps 2018)?

**Comment by hturner** [comment]
I shared some on our Slack (in the random channel) but now I realise we may not have permission to put on the website (we would need to contact the photograher: https://www.user2017.brussels/news/2017/pictures-pictures-pictures). Moreover it is just a few of us and if we started to gather "in action" photos of everyone that could be hard to organise on the page - which is why didn't add headshots when we expanded the taskforce. Perhaps discuss more at the core team meeting, but we can leave this for now.
